 /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Mikasa({ active, ...props }) {

  const { nodes, materials } =
    useGLTF(import.meta.env.BASE_URL + 'models/mikasa.glb')

  // =========================
  // MODEL
  // =========================
  const model = useRef()

  // =========================
  // BONES
  // =========================
  const leftLeg = useRef()
  const rightLeg = useRef()

  const leftArm = useRef()
  const rightArm = useRef()

  // =========================
  // KEYS
  // =========================
  const keys = useRef({})

  // =========================
  // ORIGINAL ROTATIONS
  // =========================
  const initialRotations = useRef({})

  // =========================
  // KEYBOARD
  // =========================
  useEffect(() => {

    const down = (e) => {
      keys.current[e.code] = true
    }

    const up = (e) => {
      keys.current[e.code] = false
    }

    window.addEventListener('keydown', down)
    window.addEventListener('keyup', up)

    return () => {
      window.removeEventListener('keydown', down)
      window.removeEventListener('keyup', up)
    }

  }, [])

  // =========================
  // FIND BONES
  // =========================
  useEffect(() => {

    console.log("========== BONES ==========")

    const skeleton =
      nodes.Object_179.skeleton

    skeleton.bones.forEach((bone) => {

      console.log(bone.name)

      // SAVE ORIGINAL ROTATION
      initialRotations.current[bone.name] = {
        x: bone.rotation.x,
        y: bone.rotation.y,
        z: bone.rotation.z,
      }

      // =====================
      // LEGS
      // =====================

      // LEFT LEG
      if (bone.name === 'Left_leg_03') {
        leftLeg.current = bone
      }

      // RIGHT LEG
      if (bone.name === 'Right_leg_07') {
        rightLeg.current = bone
      }

      // =====================
      // ARMS
      // =====================

      // LEFT ARM
      if (bone.name === 'Left_arm_071') {
        leftArm.current = bone
      }

      // RIGHT ARM
      if (bone.name === 'Right_arm_089') {
        rightArm.current = bone
      }

    })

    console.log("========== END ==========")

  }, [nodes])

  // =========================
  // FRAME LOOP
  // =========================
  useFrame((state, delta) => {

    if (!model.current) return

    const speed = 3 * delta
    const rotSpeed = 2 * delta

    let moving = false

    // =========================
    // ROTATION
    // =========================
    if (keys.current['ArrowLeft']) {
      model.current.rotation.y += rotSpeed
    }

    if (keys.current['ArrowRight']) {
      model.current.rotation.y -= rotSpeed
    }

    // =========================
    // MOVEMENT
    // =========================
    if (keys.current['ArrowUp']) {

      model.current.position.x -=
        Math.sin(model.current.rotation.y) * speed

      model.current.position.z -=
        Math.cos(model.current.rotation.y) * speed

      moving = true
    }

    if (keys.current['ArrowDown']) {

      model.current.position.x +=
        Math.sin(model.current.rotation.y) * speed

      model.current.position.z +=
        Math.cos(model.current.rotation.y) * speed

      moving = true
    }

    // =========================
    // WALK ANIMATION
    // =========================
    const t = state.clock.elapsedTime * 7

    if (moving) {

      // =====================
      // LEFT LEG
      // =====================
      if (leftLeg.current) {

        const base =
          initialRotations.current[leftLeg.current.name]

        leftLeg.current.rotation.x =
          base.x + Math.sin(t) * 0.7
      }

      // =====================
      // RIGHT LEG
      // =====================
      if (rightLeg.current) {

        const base =
          initialRotations.current[rightLeg.current.name]

        rightLeg.current.rotation.x =
          base.x - Math.sin(t) * 0.7
      }

      // =====================
      // LEFT ARM
      // =====================
      if (leftArm.current) {

        const base =
          initialRotations.current[leftArm.current.name]

        leftArm.current.rotation.x =
          base.x - Math.sin(t) * 0.5
      }

      // =====================
      // RIGHT ARM
      // =====================
      if (rightArm.current) {

        const base =
          initialRotations.current[rightArm.current.name]

        rightArm.current.rotation.x =
          base.x + Math.sin(t) * 0.5
      }

    } else {

      // =====================
      // RESET LEFT LEG
      // =====================
      if (leftLeg.current) {

        const base =
          initialRotations.current[leftLeg.current.name]

        leftLeg.current.rotation.x +=
          (base.x - leftLeg.current.rotation.x) * 0.1
      }

      // =====================
      // RESET RIGHT LEG
      // =====================
      if (rightLeg.current) {

        const base =
          initialRotations.current[rightLeg.current.name]

        rightLeg.current.rotation.x +=
          (base.x - rightLeg.current.rotation.x) * 0.1
      }

      // =====================
      // RESET LEFT ARM
      // =====================
      if (leftArm.current) {

        const base =
          initialRotations.current[leftArm.current.name]

        leftArm.current.rotation.x +=
          (base.x - leftArm.current.rotation.x) * 0.1
      }

      // =====================
      // RESET RIGHT ARM
      // =====================
      if (rightArm.current) {

        const base =
          initialRotations.current[rightArm.current.name]

        rightArm.current.rotation.x +=
          (base.x - rightArm.current.rotation.x) * 0.1
      }

    }

  })

  return (

    <group
      ref={model}
      position={[0, -1, 0]}
      {...props}
      dispose={null}
    >

      <group scale={0.01}>

        <group
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >

          <primitive object={nodes._rootJoint} />

          <skinnedMesh
            geometry={nodes.Object_179.geometry}
            material={materials['7_Body_1.0_0_0']}
            skeleton={nodes.Object_179.skeleton}
          />

          <skinnedMesh
            geometry={nodes.Object_180.geometry}
            material={materials['7_Hair_1.0_0_0']}
            skeleton={nodes.Object_180.skeleton}
          />

          <skinnedMesh
            geometry={nodes.Object_181.geometry}
            material={
              materials['24_Face_cheek_0.1_16.0_16']
            }
            skeleton={nodes.Object_181.skeleton}
          />

        </group>

      </group>

    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/mikasa.glb')